CREATE TABLE product_type (
  id SERIAL PRIMARY KEY,
  description VARCHAR NOT NULL,
  tax_percentage NUMERIC NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product (
  id SERIAL PRIMARY KEY,
  product_type_id BIGINT  NOT NULL ,
  description VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_type_id) REFERENCES product_type(id)
);

CREATE TABLE sales (
  id SERIAL PRIMARY KEY,
  description VARCHAR NOT NULL,
  products JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);